### ISSUE TITLE
Problems serializing Avro Schema object

### ISSUE THREAD

**Issue by a-marcel** [FasterXML/jackson-dataformat-avro#16]
Hello,

if it possible to use this in Spring Integration ?

``` java
package org.example;

import org.springframework.integration.support.json.Jackson2JsonObjectMapper;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.avro.AvroFactory;

public class AvroJsonObjectMapperFactory
{
    public static Jackson2JsonObjectMapper getMapper()
    {

        ObjectMapper mapper = new ObjectMapper(new AvroFactory());      
///     mapper.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
        return new Jackson2JsonObjectMapper(mapper);
    }
}

```

``` xml
<bean id="avroObjectMapper" class="org.example.AvroJsonObjectMapperFactory" factory-method="getMapper" />

<int:object-to-json-transformer object-mapper="avroObjectMapper" input-channel="input" output-channel="output"/>
```

if i use this configuration and put an avro object in that channel. i get:

```
org.springframework.integration.handler.LoggingHandler   - org.springframework.integration.transformer.MessageTransformationException: failed to transform message
    at org.springframework.integration.transformer.AbstractTransformer.transform(AbstractTransformer.java:44)
    at org.springframework.integration.transformer.MessageTransformingHandler.handleRequestMessage(MessageTransformingHandler.java:68)
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:170)
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:78)
    at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:74)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:219)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.access$000(AbstractPollingEndpoint.java:55)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:149)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:146)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller$1.run(AbstractPollingEndpoint.java:298)
    at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:52)
    at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
    at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:49)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:292)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.UnsupportedOperationException: Can not create generator for character-based (not byte-based) target
    at com.fasterxml.jackson.dataformat.avro.AvroFactory._nonByteTarget(AvroFactory.java:384)
    at com.fasterxml.jackson.dataformat.avro.AvroFactory._createGenerator(AvroFactory.java:355)
    at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1051)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2323)
    at org.springframework.integration.support.json.Jackson2JsonObjectMapper.toJson(Jackson2JsonObjectMapper.java:59)
    at org.springframework.integration.json.ObjectToJsonTransformer.doTransform(ObjectToJsonTransformer.java:96)
    at org.springframework.integration.transformer.AbstractTransformer.transform(AbstractTransformer.java:33)
    ... 22 more
```

Thanks

**Comment by artemik** [comment]
@cowtowncoder 
Any update on the issue? How can I convert Avro DTO to Json successfully and without all extra avro stuff, only data fields?

**Comment by cowtowncoder** [comment]
@artemik as per my earlier comment, schemas are now serializable, using standard POJO serialization. If you think further improvements are needed you can file a new issue at:
(this project is deprecated as stand-alone thing and I will disable the issue tracker again)

https://github.com/FasterXML/jackson-dataformats-binary

and explain why and what you think should be improved. Just saying "leave out avro stuff" does not explain intent well enough.

**Comment by SailendraL** [comment]
We have similar issue. We have an object created by Avro maven plugin. We can't edit the generated file. We would like to convert the object to JSON but we get an error as mentioned in original post.

**Comment by cowtowncoder** [comment]
@SailendraL If you have a problem, please file a new issue instead of commenting on old one: issue should include version information, and ideally reproduction along with description.
