### ISSUE TITLE
"Current context not an object but ARRAY" when encountering nested object and using JsonGenerator.Feature.IGNORE_UNKNOWN = true

### ISSUE THREAD

**Issue by shoeree** [FasterXML/jackson-dataformat-avro#19]
I'm trying to generate an Avro record from a Java object, using a Schema which has a subset of the fields present in the object. It looks like something like this is happening:
* The BeanSerializer attempts to serialize a nested Java object within the object I'm trying to serialize to the Schema.
* The AvroGenerator calls writeStartObject() for the nested object.
* AvroContext.createChildObjectContext() is called, which sees that the object is not in the Schema. It generates a NopWriteContext().
* The NopWriteContext's constructor sets its type to TYPE_ARRAY. (This is where I think the problem begins.)
* The BeanSerializer continues "serializing" the nested object.
* Upon finishing "serialization", the AvroGenerator calls writeEndObject().
* Unfortunately, at this point, the AvroGenerator's NopWriteContext reports that it is currently within a TYPE_ARRAY, generating the error:
```Current context not an object but ARRAY```

**Comment by cowtowncoder** [comment]
That does sound like a bug, and makes sense. Would it be possible to get simple demonstration schema, matching POJO, that triggers this?

**Comment by shoeree** [comment]
Sure thing!

**EventLog.java: Contains the top-level POJO and all nested POJOs:**
```java
package com.demonstration;

import java.util.List;

class EventID {
    public String description;
    public Integer first;
    public Integer second;
    
    public EventID(String description, Integer first, Integer second) {
        this.description = description;
        this.first = first;
        this.second = second;
    }
}

class Problem {
    public Integer x;
    public Integer y;
    
    public Problem(Integer x, Integer y) {
        this.x = x;
        this.y = y;
    }
}

class Event {
    public Integer playerCount;
    public EventID eventID;
    
    public Event(Integer playerCount, EventID eventID) {
        this.playerCount = playerCount;
        this.eventID = eventID;
    }
}

public class EventLog {
    public Integer version;
    public final Integer MAX_EVENTS = 255;
    public Byte eventCount;
    public List<Event> events;
    public List<Problem> problems;
    
    public EventLog(Integer version, Byte eventCount, List<Event> events, List<Problem> problems) {
        this.version = version;
        this.eventCount = eventCount;
        this.events = events;
        this.problems = problems;
    }
}
```
**demonstration.avsc: Contains the Avro Schema which is a subset of the fields in the POJO:**
```javascript
{
    "fields": [
        {
            "default": null,
            "name": "version",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "MAX_EVENTS",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "eventCount",
            "type": [
                "null",
                {
                    "java-class": "java.lang.Byte",
                    "type": "int"
                }
            ]
        },
        {
            "default": null,
            "name": "events",
            "type": [
                "null",
                {
                    "items": {
                        "fields": [
                            {
                                "name": "playerCount",
                                "type": [
                                    "null",
                                    "int"
                                ]
                            },  
                            {
                                "name": "eventID",
                                "type": [
                                    "null",
                                    {
                                        "fields": [
                                            {
                                                "default": null,
                                                "name": "description",
                                                "type": [
                                                    "null",
                                                    "string"
                                                ]
                                            },
                                            {
                                                "default": null,
                                                "name": "first",
                                                "type": [
                                                    "null",
                                                    "int"
                                                ]
                                            },
                                            {
                                                "default": null,
                                                "name": "second",
                                                "type": [
                                                    "null",
                                                    "int"
                                                ]
                                            }
                                        ],
                                        "name": "EventID",
                                        "namespace": "com.demonstration",
                                        "type": "record"
                                    }
                                ]
                            }
                        ],
                        "name": "Event",
                        "namespace": "com.demonstration",
                        "type": "record"
                    },
                    "java-class": "java.util.List",
                    "type": "array"
                }
            ]
        }
    ],
    "name": "EventLog",
    "namespace": "com.demonstration",
    "type": "record"
}
```

And, if you're interested, I wrote the main program in Scala below:
```scala
// Demonstration.scala
package com.demonstration

import java.io.ByteArrayInputStream

import org.apache.avro.Schema
import org.apache.avro.generic.GenericDatumReader
import org.apache.avro.generic.GenericRecord
import org.apache.avro.io.BinaryDecoder
import org.apache.avro.io.DecoderFactory

import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility
import com.fasterxml.jackson.annotation.PropertyAccessor
import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.ObjectWriter
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.dataformat.avro.AvroFactory
import com.fasterxml.jackson.dataformat.avro.AvroSchema

object Demonstration {
  val defaultAvscSource = "C:/Dev-Home/scrap/demonstration.avsc"
  
  def main(args: Array[String]) {
    val avsc = readAvsc()
    
    val sampleEvents = new java.util.ArrayList[Event](3)
    sampleEvents.add(new Event(10, new EventID("sample1", 1, 2)))
    sampleEvents.add(new Event(20, new EventID("sample2", 10, 20)))
    sampleEvents.add(new Event(30, new EventID("sample3", 100, 200)))
    
    val sampleProblems = new java.util.ArrayList[Problem](2)
    sampleProblems.add(new Problem(800, 801))
    sampleProblems.add(new Problem(900, 901))
    
    val obj = new EventLog(9999, sampleEvents.size.toByte, sampleEvents, sampleProblems)
    mapObjectToSchema(obj, avsc)
  }

  def readAvsc(source: String = defaultAvscSource): Schema = {
    val srcIO = scala.io.Source.fromFile(source)
    val avscSourceString = try srcIO.getLines mkString "\n" finally srcIO.close

    new Schema.Parser().setValidate(true).parse(avscSourceString)
  }
  
  val mapper = new ObjectMapper(new AvroFactory)
    .setVisibility(PropertyAccessor.FIELD, Visibility.PUBLIC_ONLY)
    .setVisibility(PropertyAccessor.GETTER, Visibility.NONE)
    .configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false)
    .configure(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES, false)
    .configure(JsonGenerator.Feature.IGNORE_UNKNOWN, true)
    .configure(JsonGenerator.Feature.AUTO_CLOSE_JSON_CONTENT, false)
  
  var binaryDecoder: BinaryDecoder = null
  
  def mapObjectToSchema(obj: AnyRef, schema: Schema): GenericRecord = {
    val jacksonWriter = mapper.writer[ObjectWriter](new AvroSchema(schema))
    val avroReader = new GenericDatumReader[GenericRecord](schema)
  
    // Attempt to reuse the old binary decoder to save time/space
    binaryDecoder = DecoderFactory.get.binaryDecoder(
      new ByteArrayInputStream(jacksonWriter.writeValueAsBytes(obj)), binaryDecoder)
    avroReader.read(null, binaryDecoder)
  }
  
}
```

**Comment by shoeree** [comment]
I should also note that I'm using version 2.5.4 of jackson:
```xml
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-avro</artifactId>
            <version>2.5.4</version>
        </dependency>
```

**Comment by cowtowncoder** [comment]
Perfect! Thank you for providing all the information, should be easy to reproduce.

**Comment by cowtowncoder** [comment]
Turned out to be a simple bug: `NopWriteContext` was always being created "as array", instead of object or array depending on assumed type (based on start token that was written).

**Comment by szaccaria** [comment]
Hi @cowtowncoder, 
I found something that seem inherent this problem.
I have this classes, sorry for the many:

This the annotations and configurations classes:
```java
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface MyAnnotation {
}

public class MyVersion extends VersionUtil
{
    public final static MyVersion instance = new MyVersion();
}

public class MyAnnotationIntrospector extends AnnotationIntrospector {
	private static final long serialVersionUID = 1L;
	@Override
	public Version version() {
		return MyVersion.instance.version();
	}
	@Override
	public Object findSerializer(Annotated am) {
		if (am.hasAnnotation(MyAnnotation.class)) {
			return new MySerializer();
		}
		return null;
	}
}

public class MySerializer extends JsonSerializer<Object> {
	@Override
	public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException, JsonProcessingException {
		gen.writeString("something to serializer");
	}
	@Override
	public void serializeWithType(Object value, JsonGenerator gen, SerializerProvider serializers, TypeSerializer typeSer) throws IOException {
		typeSer.writeTypePrefixForObject(value, gen);
		gen.writeFieldName("my-field");
		gen.writeString("something to serializer");
	}
}

public class MyModule extends Module {
	@Override
	public String getModuleName() {
		return "myModule";
	}
	@Override
	public Version version() {
		return MyVersion.instance.version();
	}
	@Override
	public void setupModule(SetupContext context) {
		context.appendAnnotationIntrospector(new MyAnnotationIntrospector());	
	}
}
```
This the entities:
```java
@JsonTypeInfo(use = com.fasterxml.jackson.annotation.JsonTypeInfo.Id.CLASS, include = As.PROPERTY, property = "clazz")
public abstract class Base {
	private long id;
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
}

public class Parent extends Base {
	private String nome;
	@MyAnnotation
	private Child child;
	public Parent(String nome) {
		this.nome = nome;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public Child getChild() {
		return child;
	}
	public void setChild(Child child) {
		this.child = child;
	}
}

public class Child extends Base {
	private String name;
	public Child(String name){
		this.name = name;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}
```

And now my test class

```java
public class Test {
	public static void main(String[] args) throws JsonProcessingException {

		ObjectMapper objectMapper = new ObjectMapper();
		MyModule mod = new MyModule();
		objectMapper.registerModule(mod);

		Parent parent = new Parent("parent");
		parent.setChild(new Child("child"));

		Parent[] parents = { parent };

		// work
		System.out.println(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(parent));
		
		// don't work
		System.out.println(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(parents));

	}
}
```

Like you see if you run this code, when I try to serialize the single object it work like a charm, but if i try serialize a array of this object I have the:

```
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Current context not Array but Object
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeEndArray(WriterBasedJsonGenerator.java:233)
	at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:217)
	at com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:26)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1419)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1147)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1020)
	at com.cesaco.jackson.Test.main(Test.java:25)
```

If i comment the `@JsonTypeInfo` annotation to the Base class or not set the child to the parent, all work.

I test with the 2.8.3 version of the jackson lib.

I wrong with something?

Thanks in advance

**Comment by cowtowncoder** [comment]
@szaccaria I don't see why this would be related to the original issue. Are you using Avro? If not, bug belongs under `jackson-databind`.

But one specific problem I see is with the serializer:

```java
    @Override
    public void serializeWithType(Object value, JsonGenerator gen, SerializerProvider serializers, TypeSerializer typeSer) throws IOException {
        typeSer.writeTypePrefixForObject(value, gen);
        gen.writeFieldName("my-field");
        gen.writeString("something to serializer");
    }
```

which must call `writeTypeSuffixForObject(...)` after serialization; otherwise Object/Array that was started (to contain type id) is not closed. That would cause issue like you experience, so I would fix that first.
If you still face a problem, please file a new bug for `jackson-databind`.

**Comment by szaccaria** [comment]
I apologise @cowtowncoder, you are right!
Thanks, and sorry for post in the wrong thread
